### ISSUE TITLE
support gerrit

### ISSUE THREAD

**Issue by parisni** [juacker/git-link.nvim#1]
hi.
tested with success with our internal github !

we also have gerrit. I wonder how we could support multiple url rewrite rule and let plugin user customize them. Some kind of pattern maching based on the git remote

**Comment by juacker** [comment]
Thanks for suggesting this enhancement @parisni! I've implemented a rule-based system for URL generation that allows custom URL patterns for different git platforms. I'm not familiar with gerrit, but I think it should work for it too.

You can now configure a custom rule like this:
```lua
{
    url_rules = {
        {
            pattern = "^ssh://([^:]+):29418/(.+)$",
            replace = "https://%1/plugins/gitiles/%2",
            format_url = function(base_url, params)
                return string.format("%s/+/refs/heads/%s/%s#%d",
                    base_url,
                    params.branch,
                    params.file_path,
                    params.line_number
                )
            end
        }
    }
}
```

I've updated the [README](https://github.com/juacker/git-link.nvim/blob/main/README.md) with additional details on how to configure custom rules, along with the new features that were added.

Please try it out and let me know if this meets your needs or if you'd like to see any adjustments.

**Comment by parisni** [comment]
Brillant, this works great, the gerrit example you provide in the readme works fine !
