### ISSUE TITLE
support range of lines

### ISSUE THREAD

**Issue by parisni** [juacker/git-link.nvim#3]
hi !

currently we can share a given row in a given file. Might be useful to share a range of row in a file, [like that](https://github.com/juacker/git-link.nvim/blob/main/lua/git-link/config.lua#L7-L10)

**Comment by juacker** [comment]
You read my mind, this was next in my to-do list. I'll try to have it ready this week..

**Comment by juacker** [comment]
I've added support for range of lines.

You will need to apply two configuration changes for it to work:

- In your LazyVim config, you have to add ` mode = { "n", "x" }` so the command is also executed in visual mode.
- the var name `line_number` has been renamed to `start_line`. This breaks backwards compatibility of your current gerrit config, but I think it will make things clearer for future users. You will need to update your gerrit rule so it uses the new variable name.

I've updated the [README](https://github.com/juacker/git-link.nvim/blob/main/README.md), including the gerrit example to work with the new updates, so you should not have any issue.

Please let me know if this change worked for you.

**Comment by parisni** [comment]
Many thanks @juacker. I took longer to test than you did to code the functionality.

Works great !
